apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
        - name: cursos
          image: jsanchez22/msvc-cursos:latest
          ports:
            - containerPort: 8002
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP                 
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: password
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: usuario_url
            - name: spring_profiles_active
              value: dev