apiVersion: v1
kind: PersistentVolume
metadata:
  name: coky-mysql-pv
spec:
  capacity:
     storage: 2Gi
  volumeMode: Filesystem
  storageClassName: ""
  #storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0cc6a11d380e98369
#  hostPath:
#    path: /var/lib/mysql
#    type: DirectoryOrCreate