apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coky-mysql-pvc
spec:
  volumeName: coky-mysql-pv
  accessModes:
    - ReadWriteMany
#   - ReadWriteOnce
  storageClassName: ""
# storageClassName: "standard"
  resources:
    requests:
      storage: 2Gi
